### ISSUE TITLE
modify HEX IDs

### ISSUE THREAD

**Issue by alexanderdross** [TheMiNuS/Stratux-daughter-board#2]
Currently the RF chips use the RPI's CPU ID as the HEX ID for TX purposes.
Here an overwriting/ changing of HEX IDs of the two RF chips is recommended.
As an example Stratux Web Interface > Settings > Configuration > Ownship Mode - the HEX ID which is uesd for the Ownship mode should be used for the RF chips instead. 
This enables to use your aircraft's ADS-B out Transponder ID for the RF chips
![stratux-web-interface](https://user-images.githubusercontent.com/9116818/153705124-160282a4-bcb0-453f-8700-f2d6842c9295.png)

**Comment by TheMiNuS** [comment]
The hex code can be changed for ogntp via the stratux interface. For the second chip it depend on the code people decide to use but for now this chip is not used/driven by stratux so it's a free chip for a personal usage.

As it's code related I will close this one.
